steps:
  - name: 'python'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install poetry
        poetry config virtualenvs.create false
        poetry install
        poetry run uvicorn app.main:app --host 0.0.0.0 --port 8080

timeout: 900s
