erDiagram
    USERS {
        ObjectId _id
        string email
        string name
        string hashed_password
        string avatar_url
        enum gender
        datetime created_at
        datetime updated_at
    }

    CONTENTS {
        ObjectId _id
        string title
        string description
        array genres
        int year
        boolean type
        string image_url
        float average_rating
        int num_likes
        int num_watches
        int num_ratings
        int num_comments
        datetime created_at
        datetime updated_at
    }

    COLLECTIONS {
        ObjectId _id
        string title
        boolean is_public
        ObjectId user_id
        array content_ids
        datetime created_at
        datetime updated_at
    }

    COMMENTS {
        ObjectId _id
        string text
        ObjectId content_id
        ObjectId user_id
        datetime created_at
        datetime updated_at
    }

    USER_CONTENTS {
        ObjectId _id
        ObjectId user_id
        ObjectId content_id
        boolean is_liked
        boolean is_watched
        boolean in_watchlist
        int rated
        datetime last_interacted_at
    }

    %% İlişkiler
    USERS ||--o{ COLLECTIONS : "oluşturur"
    USERS ||--o{ COMMENTS : "yazar"
    USERS ||--o{ USER_CONTENTS : "etkileşim_kurar"
    
    CONTENTS ||--o{ COMMENTS : "alır"
    CONTENTS ||--o{ USER_CONTENTS : "etkileşim_alır"
    CONTENTS }o--o{ COLLECTIONS : "içerir" 