[project]
name = "cinemate"
version = "0.1.0"
description = "FastAPI backend for the CineMate movie and series tracking application"
authors = [{ name = "Muhammet Berk", email = "muhammetberk561@gmail.com" }]
license = { file = "LICENSE" }
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi (>=0.115.12,<0.116.0)",
    "uvicorn (>=0.34.0,<0.35.0)",
    "python-dotenv (>=1.1.0,<2.0.0)",
    "pydantic[email] (>=2.11.3,<3.0.0)",
    "pydantic-settings (>=2.2.1,<3.0.0)",
    "passlib[bcrypt] (>=1.7.4,<2.0.0)",
    "python-jose (>=3.4.0,<4.0.0)",
    "pymongo (>=4.12.0,<5.0.0)",
    "motor (>=3.7.0,<4.0.0)",
    "python-multipart (>=0.0.20,<0.0.21)",
    "requests (>=2.32.3,<3.0.0)",
    "behave (>=1.2.6,<2.0.0)",
    "allure-behave (>=2.14.0,<3.0.0)",
    "sentence-transformers (>=4.1.0,<5.0.0)",
    "pandas (>=2.3.0,<3.0.0)",
    "matplotlib (>=3.10.3,<4.0.0)",
    "seaborn (>=0.13.2,<0.14.0)",
    "torch (==2.7.1+cpu)",
    "torchvision (==0.22.1+cpu)",
    "numpy (==1.26.4)",
    "locust (>=2.37.11,<3.0.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
[tool.poetry.group.dev.dependencies]
black = "^25.1.0"
isort = "^6.0.1"
behave = "^1.2.6"


[[tool.poetry.source]]
name = "pytorch_cpu"
url = "https://download.pytorch.org/whl/cpu"
priority = "explicit"

[tool.poetry.dependencies]
torch = { version = "==2.7.1+cpu", source = "pytorch_cpu" }
torchvision = { version = "==0.22.1+cpu", source = "pytorch_cpu" }
[tool.poetry]
package-mode = false
