erDiagram
    USER {
        ObjectId _id
        string email
        string password
        string name
    }

    CONTENT {
        ObjectId _id
        string title
        string description
        string[] genres
        int year
        float average_rating
        int num_likes
        int num_watches
        int num_ratings
        int num_comments
    }

    USER_CONTENT {
        ObjectId user_id
        ObjectId content_id
        boolean is_liked
        boolean is_watched
        boolean in_watchlist
        float rated
        datetime last_interacted_at
    }

    COLLECTION {
        ObjectId _id
        ObjectId user_id
        string title
        ObjectId[] content_ids
    }

    COMMENT {
        ObjectId _id
        ObjectId content_id
        ObjectId user_id
        string text
        datetime created_at
    }

    %% Relationships
    USER ||--o{ USER_CONTENT : creates
    CONTENT ||--o{ USER_CONTENT : is
    USER ||--o{ COLLECTION : owns
    COLLECTION ||--|{ CONTENT : contains
    USER ||--o{ COMMENT : writes
    CONTENT ||--o{ COMMENT : receives
